const Sequelize = require("sequelize");
const db = require("./db");
const BranchOffice = require("./BranchOffice.models");
const Horary = require("./Horary.models");
const User = require("./User.models");
const Confirmation = require("./Confirmation.models");
const ReasonCancellation = require("./ReasonCancellation.models");

class Turn extends Sequelize.Model {
  static turnsByUser(userId) {
    return Turn.findAll({
      where: {
        userId,
      },
    });
  }

  static checkTurns(turnDate, horaryId, branch_office_id) {
    return Turn.findAll({
      where: {
        turn_date: turnDate,
        horary_id: horaryId,
        confirmation_id: "pending",
        branch_office_id: branch_office_id,
      },
    });
  }
}
Turn.init(
  {
    //Fecha del turno
    turn_date: {
      type: Sequelize.DATEONLY,
      allowNull: false,
    },

    //Hora del turno:
    //La va a traer desde la tabla "Horary"

    //Día en el cual se reservó el turno
    reservation_date: {
      type: Sequelize.DATEONLY,
      allowNull: false,
    },
    //Hora en la cual se reservó el turno
    reservation_time: {
      type: Sequelize.TIME,
      allowNull: false,
    },
    confirmation_id: {
      type: Sequelize.STRING,
      allowNull: false,
      references: {
        model: Confirmation,
        key: "id",
      },
    },
    reason_cancellation_id: {
      type: Sequelize.INTEGER,
      references: {
        model: ReasonCancellation,
        key: "id",
      },
    },
    user_id: {
      type: Sequelize.INTEGER,
      allowNull: false,
      references: {
        model: User,
        key: "id",
      },
    },
    branch_office_id: {
      type: Sequelize.INTEGER,
      allowNull: false,
      references: {
        model: BranchOffice,
        key: "id",
      },
    },
    horary_id: {
      type: Sequelize.TIME,
      allowNull: false,
      references: {
        model: Horary,
        key: "id",
      },
    },
    full_name: {
      type: Sequelize.STRING,
      allowNull: false,
    },
    phone_number: {
      type: Sequelize.STRING,
      allowNull: false,
    },
  },
  { sequelize: db, modelName: "turn" }
);
Turn.sync()
  .then(() => {
    return Turn.count();
  })
  .then((count) => {
    if (count === 0) {
      const turnsToCreate = [
        {
          turn_date: "2023-07-17",
          reservation_date: "2023-06-30",
          reservation_time: "10:45",
          confirmation_id: "cancelled",
          reason_cancellation_id: 5,
          user_id: 3,
          branch_office_id: 1,
          horary_id: "21:00",
          full_name: "Rodrigo Arismendi",
          phone_number: "2499914840",
        },
        {
          turn_date: "2023-11-10",
          reservation_date: "2023-10-21",
          reservation_time: "13:00",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 2,
          branch_office_id: 1,
          horary_id: "14:30",
          full_name: "Rodrigo Arismendi",
          phone_number: "8056432637",
        },
        {
          turn_date: "2023-11-24",
          reservation_date: "2023-11-07",
          reservation_time: "09:00",
          confirmation_id: "cancelled",
          reason_cancellation_id: 3,
          user_id: 3,
          branch_office_id: 2,
          horary_id: "21:15",
          full_name: "Rodrigo Lezcano",
          phone_number: "7499829036",
        },
        {
          turn_date: "2023-02-23",
          reservation_date: "2023-02-10",
          reservation_time: "20:15",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 2,
          branch_office_id: 2,
          horary_id: "10:30",
          full_name: "Juan Lezcano",
          phone_number: "4565026659",
        },
        {
          turn_date: "2023-02-07",
          reservation_date: "2023-01-29",
          reservation_time: "19:30",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 3,
          branch_office_id: 2,
          horary_id: "12:15",
          full_name: "Fabiola Escalera",
          phone_number: "8807131270",
        },
        {
          turn_date: "2023-07-23",
          reservation_date: "2023-07-04",
          reservation_time: "17:30",
          confirmation_id: "cancelled",
          reason_cancellation_id: 1,
          user_id: 3,
          branch_office_id: 1,
          horary_id: "14:15",
          full_name: "Fabiola Arismendi",
          phone_number: "6612190553",
        },
        {
          turn_date: "2023-09-11",
          reservation_date: "2023-08-24",
          reservation_time: "17:00",
          confirmation_id: "cancelled",
          reason_cancellation_id: 4,
          user_id: 3,
          branch_office_id: 2,
          horary_id: "13:00",
          full_name: "Juan Pablo Glave",
          phone_number: "7789180295",
        },
        {
          turn_date: "2023-09-10",
          reservation_date: "2023-09-01",
          reservation_time: "15:45",
          confirmation_id: "confirmed",
          reason_cancellation_id: undefined,
          user_id: 2,
          branch_office_id: 1,
          horary_id: "14:45",
          full_name: "Juan Pablo Lutrario",
          phone_number: "5609928882",
        },
        {
          turn_date: "2023-03-06",
          reservation_date: "2023-02-15",
          reservation_time: "14:45",
          confirmation_id: "confirmed",
          reason_cancellation_id: undefined,
          user_id: 2,
          branch_office_id: 2,
          horary_id: "15:15",
          full_name: "Lucas Arismendi",
          phone_number: "8444758781",
        },
        {
          turn_date: "2023-12-08",
          reservation_date: "2023-11-18",
          reservation_time: "21:30",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 2,
          branch_office_id: 2,
          horary_id: "14:30",
          full_name: "Fabiola Lezcano",
          phone_number: "2634611044",
        },
        {
          turn_date: "2023-02-24",
          reservation_date: "2023-02-23",
          reservation_time: "14:45",
          confirmation_id: "confirmed",
          reason_cancellation_id: undefined,
          user_id: 3,
          branch_office_id: 1,
          horary_id: "16:00",
          full_name: "Juan Pablo Arismendi",
          phone_number: "3068756334",
        },
        {
          turn_date: "2023-07-12",
          reservation_date: "2023-07-02",
          reservation_time: "21:45",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 3,
          branch_office_id: 2,
          horary_id: "10:45",
          full_name: "Rodrigo Escalera",
          phone_number: "7686521946",
        },
        {
          turn_date: "2023-02-21",
          reservation_date: "2023-02-03",
          reservation_time: "18:45",
          confirmation_id: "confirmed",
          reason_cancellation_id: undefined,
          user_id: 3,
          branch_office_id: 1,
          horary_id: "14:30",
          full_name: "Fabiola Escalera",
          phone_number: "5184927015",
        },
        {
          turn_date: "2023-07-15",
          reservation_date: "2023-06-24",
          reservation_time: "18:30",
          confirmation_id: "cancelled",
          reason_cancellation_id: 5,
          user_id: 2,
          branch_office_id: 1,
          horary_id: "20:00",
          full_name: "Fabiola Escalera",
          phone_number: "5965276780",
        },
        {
          turn_date: "2023-07-12",
          reservation_date: "2023-06-24",
          reservation_time: "08:15",
          confirmation_id: "cancelled",
          reason_cancellation_id: 3,
          user_id: 2,
          branch_office_id: 1,
          horary_id: "20:30",
          full_name: "Juan Pablo Arismendi",
          phone_number: "3111444995",
        },
        {
          turn_date: "2023-05-21",
          reservation_date: "2023-05-15",
          reservation_time: "18:00",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 2,
          branch_office_id: 2,
          horary_id: "07:30",
          full_name: "Lucas Escalera",
          phone_number: "7828789917",
        },
        {
          turn_date: "2023-07-20",
          reservation_date: "2023-07-08",
          reservation_time: "17:45",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 3,
          branch_office_id: 2,
          horary_id: "18:45",
          full_name: "Juan Pablo Lezcano",
          phone_number: "8721014320",
        },
        {
          turn_date: "2023-02-03",
          reservation_date: "2023-01-13",
          reservation_time: "13:30",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 2,
          branch_office_id: 1,
          horary_id: "10:45",
          full_name: "Juan Pablo Arismendi",
          phone_number: "4266312242",
        },
        {
          turn_date: "2023-11-24",
          reservation_date: "2023-11-11",
          reservation_time: "15:45",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 2,
          branch_office_id: 2,
          horary_id: "07:30",
          full_name: "Juan Arismendi",
          phone_number: "7025758171",
        },
        {
          turn_date: "2023-07-14",
          reservation_date: "2023-07-13",
          reservation_time: "15:15",
          confirmation_id: "cancelled",
          reason_cancellation_id: 1,
          user_id: 2,
          branch_office_id: 1,
          horary_id: "16:45",
          full_name: "Juan Pablo Lezcano",
          phone_number: "1997141775",
        },
        {
          turn_date: "2023-04-27",
          reservation_date: "2023-04-20",
          reservation_time: "16:45",
          confirmation_id: "confirmed",
          reason_cancellation_id: undefined,
          user_id: 3,
          branch_office_id: 1,
          horary_id: "20:30",
          full_name: "Lucas Arismendi",
          phone_number: "5464849178",
        },
        {
          turn_date: "2023-09-07",
          reservation_date: "2023-08-24",
          reservation_time: "18:30",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 3,
          branch_office_id: 1,
          horary_id: "08:30",
          full_name: "Juan Glave",
          phone_number: "3241626823",
        },
        {
          turn_date: "2023-12-23",
          reservation_date: "2023-12-03",
          reservation_time: "15:00",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 3,
          branch_office_id: 2,
          horary_id: "10:30",
          full_name: "Rodrigo Glave",
          phone_number: "3163232310",
        },
        {
          turn_date: "2023-03-19",
          reservation_date: "2023-02-27",
          reservation_time: "19:00",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 2,
          branch_office_id: 2,
          horary_id: "12:00",
          full_name: "Fabiola Arismendi",
          phone_number: "4502547658",
        },
        {
          turn_date: "2023-04-18",
          reservation_date: "2023-04-01",
          reservation_time: "19:45",
          confirmation_id: "cancelled",
          reason_cancellation_id: 4,
          user_id: 3,
          branch_office_id: 1,
          horary_id: "17:00",
          full_name: "Fabiola Lezcano",
          phone_number: "7649213346",
        },
        {
          turn_date: "2023-09-03",
          reservation_date: "2023-08-26",
          reservation_time: "11:45",
          confirmation_id: "confirmed",
          reason_cancellation_id: undefined,
          user_id: 2,
          branch_office_id: 2,
          horary_id: "11:45",
          full_name: "Juan Glave",
          phone_number: "9214243109",
        },
        {
          turn_date: "2023-05-22",
          reservation_date: "2023-05-13",
          reservation_time: "10:00",
          confirmation_id: "cancelled",
          reason_cancellation_id: 2,
          user_id: 2,
          branch_office_id: 1,
          horary_id: "14:30",
          full_name: "Lucas Escalera",
          phone_number: "8140389190",
        },
        {
          turn_date: "2023-04-09",
          reservation_date: "2023-03-25",
          reservation_time: "16:30",
          confirmation_id: "cancelled",
          reason_cancellation_id: 3,
          user_id: 2,
          branch_office_id: 1,
          horary_id: "14:30",
          full_name: "Lucas Lutrario",
          phone_number: "5676810849",
        },
        {
          turn_date: "2023-10-21",
          reservation_date: "2023-10-17",
          reservation_time: "15:00",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 3,
          branch_office_id: 1,
          horary_id: "16:30",
          full_name: "Fabiola Glave",
          phone_number: "8493101659",
        },
        {
          turn_date: "2023-05-16",
          reservation_date: "2023-05-04",
          reservation_time: "21:15",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 2,
          branch_office_id: 2,
          horary_id: "21:00",
          full_name: "Juan Glave",
          phone_number: "3462208480",
        },
        {
          turn_date: "2023-05-01",
          reservation_date: "2023-04-14",
          reservation_time: "17:30",
          confirmation_id: "cancelled",
          reason_cancellation_id: 1,
          user_id: 2,
          branch_office_id: 1,
          horary_id: "18:15",
          full_name: "Juan Lezcano",
          phone_number: "7391907997",
        },
        {
          turn_date: "2023-10-01",
          reservation_date: "2023-09-29",
          reservation_time: "13:15",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 2,
          branch_office_id: 1,
          horary_id: "18:00",
          full_name: "Juan Pablo Escalera",
          phone_number: "1754674908",
        },
        {
          turn_date: "2023-01-10",
          reservation_date: "2022-12-24",
          reservation_time: "19:30",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 2,
          branch_office_id: 2,
          horary_id: "10:00",
          full_name: "Fabiola Arismendi",
          phone_number: "5575668120",
        },
        {
          turn_date: "2023-05-27",
          reservation_date: "2023-05-08",
          reservation_time: "14:45",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 2,
          branch_office_id: 2,
          horary_id: "16:00",
          full_name: "Juan Arismendi",
          phone_number: "3268188455",
        },
        {
          turn_date: "2023-02-06",
          reservation_date: "2023-02-05",
          reservation_time: "09:15",
          confirmation_id: "confirmed",
          reason_cancellation_id: undefined,
          user_id: 2,
          branch_office_id: 2,
          horary_id: "14:15",
          full_name: "Lucas Lezcano",
          phone_number: "5064231754",
        },
        {
          turn_date: "2023-06-06",
          reservation_date: "2023-06-05",
          reservation_time: "12:30",
          confirmation_id: "confirmed",
          reason_cancellation_id: undefined,
          user_id: 2,
          branch_office_id: 2,
          horary_id: "16:45",
          full_name: "Fabiola Glave",
          phone_number: "3228200387",
        },
        {
          turn_date: "2023-02-22",
          reservation_date: "2023-02-17",
          reservation_time: "07:15",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 2,
          branch_office_id: 1,
          horary_id: "10:15",
          full_name: "Rodrigo Arismendi",
          phone_number: "1605718184",
        },
        {
          turn_date: "2023-06-05",
          reservation_date: "2023-05-29",
          reservation_time: "07:15",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 2,
          branch_office_id: 1,
          horary_id: "15:30",
          full_name: "Fabiola Glave",
          phone_number: "5931315982",
        },
        {
          turn_date: "2023-06-12",
          reservation_date: "2023-06-05",
          reservation_time: "12:00",
          confirmation_id: "cancelled",
          reason_cancellation_id: 3,
          user_id: 2,
          branch_office_id: 1,
          horary_id: "07:30",
          full_name: "Juan Arismendi",
          phone_number: "8283624175",
        },
        {
          turn_date: "2023-01-12",
          reservation_date: "2022-12-26",
          reservation_time: "20:00",
          confirmation_id: "cancelled",
          reason_cancellation_id: 5,
          user_id: 2,
          branch_office_id: 1,
          horary_id: "07:30",
          full_name: "Juan Glave",
          phone_number: "6400267414",
        },
        {
          turn_date: "2023-05-08",
          reservation_date: "2023-05-01",
          reservation_time: "12:45",
          confirmation_id: "cancelled",
          reason_cancellation_id: 4,
          user_id: 2,
          branch_office_id: 2,
          horary_id: "11:00",
          full_name: "Juan Pablo Lezcano",
          phone_number: "8836681458",
        },
        {
          turn_date: "2023-01-09",
          reservation_date: "2023-01-02",
          reservation_time: "16:00",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 3,
          branch_office_id: 1,
          horary_id: "07:30",
          full_name: "Fabiola Glave",
          phone_number: "3301604969",
        },
        {
          turn_date: "2023-11-17",
          reservation_date: "2023-11-01",
          reservation_time: "11:45",
          confirmation_id: "cancelled",
          reason_cancellation_id: 2,
          user_id: 2,
          branch_office_id: 2,
          horary_id: "19:00",
          full_name: "Fabiola Escalera",
          phone_number: "4331018846",
        },
        {
          turn_date: "2023-04-13",
          reservation_date: "2023-03-28",
          reservation_time: "08:00",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 3,
          branch_office_id: 2,
          horary_id: "18:45",
          full_name: "Juan Lezcano",
          phone_number: "1279383358",
        },
        {
          turn_date: "2023-07-25",
          reservation_date: "2023-07-12",
          reservation_time: "13:45",
          confirmation_id: "confirmed",
          reason_cancellation_id: undefined,
          user_id: 2,
          branch_office_id: 2,
          horary_id: "10:30",
          full_name: "Rodrigo Escalera",
          phone_number: "2645918237",
        },
        {
          turn_date: "2023-05-11",
          reservation_date: "2023-04-28",
          reservation_time: "18:00",
          confirmation_id: "confirmed",
          reason_cancellation_id: undefined,
          user_id: 2,
          branch_office_id: 2,
          horary_id: "11:00",
          full_name: "Lucas Glave",
          phone_number: "1153898124",
        },
        {
          turn_date: "2023-08-24",
          reservation_date: "2023-08-21",
          reservation_time: "11:00",
          confirmation_id: "confirmed",
          reason_cancellation_id: undefined,
          user_id: 2,
          branch_office_id: 2,
          horary_id: "17:00",
          full_name: "Rodrigo Lezcano",
          phone_number: "6844396219",
        },
        {
          turn_date: "2023-08-12",
          reservation_date: "2023-08-06",
          reservation_time: "15:45",
          confirmation_id: "cancelled",
          reason_cancellation_id: 5,
          user_id: 3,
          branch_office_id: 1,
          horary_id: "11:30",
          full_name: "Juan Pablo Lezcano",
          phone_number: "3577190358",
        },
        {
          turn_date: "2023-03-01",
          reservation_date: "2023-02-20",
          reservation_time: "17:30",
          confirmation_id: "cancelled",
          reason_cancellation_id: 5,
          user_id: 3,
          branch_office_id: 1,
          horary_id: "08:00",
          full_name: "Rodrigo Arismendi",
          phone_number: "2109238348",
        },
        {
          turn_date: "2023-03-19",
          reservation_date: "2023-03-18",
          reservation_time: "17:45",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 2,
          branch_office_id: 2,
          horary_id: "13:30",
          full_name: "Fabiola Lezcano",
          phone_number: "5946618152",
        },
      ];
      return Turn.bulkCreate(turnsToCreate);
    }
    return Promise.resolve(); // No es necesario devolver nada si ya hay razones de cancelacióon
  });

module.exports = Turn;
