const Sequelize = require("sequelize");
const db = require("./db");
const BranchOffice = require("./BranchOffice.models");
const Horary = require("./Horary.models");
const User = require("./User.models");
const Confirmation = require("./Confirmation.models");
const ReasonCancellation = require("./ReasonCancellation.models");

class Turn extends Sequelize.Model {
  static turnsByUser(userId) {
    return Turn.findAll({
      where: {
        userId,
      },
    });
  }

  static checkTurns(turnDate, horaryId, branch_office_id) {
    return Turn.findAll({
      where: {
        turn_date: turnDate,
        horary_id: horaryId,
        confirmation_id: "pending",
        branch_office_id: branch_office_id,
      },
    });
  }
}
Turn.init(
  {
    //Fecha del turno
    turn_date: {
      type: Sequelize.DATEONLY,
      allowNull: false,
    },

    //Hora del turno:
    //La va a traer desde la tabla "Horary"

    //Día en el cual se reservó el turno
    reservation_date: {
      type: Sequelize.DATEONLY,
      allowNull: false,
    },
    //Hora en la cual se reservó el turno
    reservation_time: {
      type: Sequelize.TIME,
      allowNull: false,
    },
    confirmation_id: {
      type: Sequelize.STRING,
      allowNull: false,
      references: {
        model: Confirmation,
        key: "id",
      },
    },
    reason_cancellation_id: {
      type: Sequelize.INTEGER,
      references: {
        model: ReasonCancellation,
        key: "id",
      },
    },
    user_id: {
      type: Sequelize.INTEGER,
      allowNull: false,
      references: {
        model: User,
        key: "id",
      },
    },
    branch_office_id: {
      type: Sequelize.INTEGER,
      allowNull: false,
      references: {
        model: BranchOffice,
        key: "id",
      },
    },
    horary_id: {
      type: Sequelize.TIME,
      allowNull: false,
      references: {
        model: Horary,
        key: "id",
      },
    },
    full_name: {
      type: Sequelize.STRING,
      allowNull: false,
    },
    phone_number: {
      type: Sequelize.STRING,
      allowNull: false,
    },
  },
  { sequelize: db, modelName: "turn" }
);
Turn.sync()
  .then(() => {
    return Turn.count();
  })
  .then((count) => {
    if (count === 0) {
      const turnsToCreate = [
        {
          turn_date: "2023-10-18",
          reservation_date: "2023-09-27",
          reservation_time: "11:45",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "16:30",
          full_name: "Juan Lezcano",
          phone_number: "5507087072",
        },
        {
          turn_date: "2023-04-23",
          reservation_date: "2023-04-11",
          reservation_time: "14:15",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "09:30",
          full_name: "Juan Pablo Arismendi",
          phone_number: "5581829066",
        },
        {
          turn_date: "2023-08-26",
          reservation_date: "2023-08-20",
          reservation_time: "18:30",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "21:15",
          full_name: "Fabiola Glave",
          phone_number: "3337349071",
        },
        {
          turn_date: "2023-08-02",
          reservation_date: "2023-07-30",
          reservation_time: "09:15",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "18:15",
          full_name: "Rodrigo Glave",
          phone_number: "9880910136",
        },
        {
          turn_date: "2023-06-09",
          reservation_date: "2023-06-02",
          reservation_time: "14:30",
          confirmation_id: "confirmed",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "18:15",
          full_name: "Fabiola Glave",
          phone_number: "1087084837",
        },
        {
          turn_date: "2023-05-15",
          reservation_date: "2023-05-02",
          reservation_time: "14:45",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "11:30",
          full_name: "Juan Glave",
          phone_number: "4062555601",
        },
        {
          turn_date: "2023-01-22",
          reservation_date: "2023-01-13",
          reservation_time: "13:30",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "14:45",
          full_name: "Juan Lutrario",
          phone_number: "8228134349",
        },
        {
          turn_date: "2023-05-28",
          reservation_date: "2023-05-21",
          reservation_time: "08:00",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "10:30",
          full_name: "Lucas Glave",
          phone_number: "7974709164",
        },
        {
          turn_date: "2023-07-18",
          reservation_date: "2023-07-12",
          reservation_time: "12:45",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "10:30",
          full_name: "Juan Pablo Escalera",
          phone_number: "2095457810",
        },
        {
          turn_date: "2023-07-06",
          reservation_date: "2023-06-22",
          reservation_time: "21:15",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "20:15",
          full_name: "Juan Glave",
          phone_number: "3976217648",
        },
        {
          turn_date: "2023-01-19",
          reservation_date: "2023-01-13",
          reservation_time: "10:00",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "16:30",
          full_name: "Fabiola Glave",
          phone_number: "2751243461",
        },
        {
          turn_date: "2023-10-24",
          reservation_date: "2023-10-10",
          reservation_time: "19:15",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "20:15",
          full_name: "Rodrigo Lezcano",
          phone_number: "6213402323",
        },
        {
          turn_date: "2023-07-08",
          reservation_date: "2023-07-05",
          reservation_time: "14:30",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "21:15",
          full_name: "Juan Glave",
          phone_number: "9788900331",
        },
        {
          turn_date: "2023-12-05",
          reservation_date: "2023-11-25",
          reservation_time: "12:00",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "17:15",
          full_name: "Juan Pablo Escalera",
          phone_number: "8067559706",
        },
        {
          turn_date: "2023-06-11",
          reservation_date: "2023-06-08",
          reservation_time: "20:15",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "07:30",
          full_name: "Juan Glave",
          phone_number: "2060169652",
        },
        {
          turn_date: "2023-09-15",
          reservation_date: "2023-09-05",
          reservation_time: "10:00",
          confirmation_id: "confirmed",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "14:45",
          full_name: "Rodrigo Lezcano",
          phone_number: "4061854110",
        },
        {
          turn_date: "2023-05-09",
          reservation_date: "2023-04-22",
          reservation_time: "15:00",
          confirmation_id: "confirmed",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "18:15",
          full_name: "Fabiola Glave",
          phone_number: "9326851573",
        },
        {
          turn_date: "2023-02-19",
          reservation_date: "2023-02-18",
          reservation_time: "17:45",
          confirmation_id: "confirmed",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "12:45",
          full_name: "Rodrigo Arismendi",
          phone_number: "4030022780",
        },
        {
          turn_date: "2023-01-21",
          reservation_date: "2023-01-12",
          reservation_time: "12:15",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "15:15",
          full_name: "Lucas Escalera",
          phone_number: "8134226498",
        },
        {
          turn_date: "2023-08-23",
          reservation_date: "2023-08-09",
          reservation_time: "19:00",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "11:15",
          full_name: "Juan Arismendi",
          phone_number: "7870448129",
        },
        {
          turn_date: "2023-06-15",
          reservation_date: "2023-06-02",
          reservation_time: "08:30",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "17:45",
          full_name: "Rodrigo Lutrario",
          phone_number: "5520077906",
        },
        {
          turn_date: "2023-12-08",
          reservation_date: "2023-11-24",
          reservation_time: "10:00",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "17:00",
          full_name: "Juan Pablo Arismendi",
          phone_number: "4403574013",
        },
        {
          turn_date: "2023-07-02",
          reservation_date: "2023-06-26",
          reservation_time: "12:00",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "15:15",
          full_name: "Fabiola Lezcano",
          phone_number: "5542750554",
        },
        {
          turn_date: "2023-02-28",
          reservation_date: "2023-02-08",
          reservation_time: "07:30",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "07:30",
          full_name: "Rodrigo Lutrario",
          phone_number: "8447434996",
        },
        {
          turn_date: "2023-07-21",
          reservation_date: "2023-07-05",
          reservation_time: "15:45",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "15:00",
          full_name: "Fabiola Lezcano",
          phone_number: "5357476840",
        },
        {
          turn_date: "2023-11-13",
          reservation_date: "2023-11-02",
          reservation_time: "10:30",
          confirmation_id: "confirmed",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "10:30",
          full_name: "Lucas Lezcano",
          phone_number: "8600581085",
        },
        {
          turn_date: "2023-07-07",
          reservation_date: "2023-06-30",
          reservation_time: "08:00",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "10:30",
          full_name: "Juan Escalera",
          phone_number: "3520498600",
        },
        {
          turn_date: "2023-03-23",
          reservation_date: "2023-03-05",
          reservation_time: "08:30",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "07:30",
          full_name: "Juan Lutrario",
          phone_number: "2767801506",
        },
        {
          turn_date: "2023-03-04",
          reservation_date: "2023-02-11",
          reservation_time: "10:00",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "11:00",
          full_name: "Juan Pablo Lutrario",
          phone_number: "5980852465",
        },
        {
          turn_date: "2023-04-01",
          reservation_date: "2023-03-11",
          reservation_time: "15:30",
          confirmation_id: "confirmed",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "14:30",
          full_name: "Juan Pablo Glave",
          phone_number: "4282149018",
        },
        {
          turn_date: "2023-07-10",
          reservation_date: "2023-06-21",
          reservation_time: "08:15",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "18:00",
          full_name: "Juan Pablo Lezcano",
          phone_number: "3185898244",
        },
        {
          turn_date: "2023-02-28",
          reservation_date: "2023-02-14",
          reservation_time: "13:15",
          confirmation_id: "cancelled",
          reason_cancellation_id: 2,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "21:15",
          full_name: "Juan Lutrario",
          phone_number: "6246552253",
        },
        {
          turn_date: "2023-11-16",
          reservation_date: "2023-11-02",
          reservation_time: "12:30",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "15:45",
          full_name: "Juan Lutrario",
          phone_number: "2769321605",
        },
        {
          turn_date: "2023-12-07",
          reservation_date: "2023-11-27",
          reservation_time: "13:30",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "07:30",
          full_name: "Juan Lutrario",
          phone_number: "1428959287",
        },
        {
          turn_date: "2023-07-10",
          reservation_date: "2023-07-06",
          reservation_time: "17:45",
          confirmation_id: "cancelled",
          reason_cancellation_id: 5,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "20:45",
          full_name: "Juan Lezcano",
          phone_number: "3185673200",
        },
        {
          turn_date: "2023-11-01",
          reservation_date: "2023-10-21",
          reservation_time: "20:00",
          confirmation_id: "confirmed",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "19:00",
          full_name: "Fabiola Glave",
          phone_number: "5738546523",
        },
        {
          turn_date: "2023-12-12",
          reservation_date: "2023-11-27",
          reservation_time: "07:45",
          confirmation_id: "absence",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "19:45",
          full_name: "Lucas Lutrario",
          phone_number: "4213018707",
        },
        {
          turn_date: "2023-07-26",
          reservation_date: "2023-07-11",
          reservation_time: "10:00",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "10:15",
          full_name: "Rodrigo Arismendi",
          phone_number: "6079310664",
        },
        {
          turn_date: "2023-10-19",
          reservation_date: "2023-10-18",
          reservation_time: "15:45",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "10:30",
          full_name: "Juan Pablo Escalera",
          phone_number: "6425683132",
        },
        {
          turn_date: "2023-03-19",
          reservation_date: "2023-03-06",
          reservation_time: "09:45",
          confirmation_id: "cancelled",
          reason_cancellation_id: 3,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "09:15",
          full_name: "Fabiola Glave",
          phone_number: "5793519347",
        },
        {
          turn_date: "2023-03-24",
          reservation_date: "2023-03-15",
          reservation_time: "07:00",
          confirmation_id: "cancelled",
          reason_cancellation_id: 3,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "16:30",
          full_name: "Juan Lezcano",
          phone_number: "5096876108",
        },
        {
          turn_date: "2023-08-20",
          reservation_date: "2023-08-05",
          reservation_time: "15:15",
          confirmation_id: "cancelled",
          reason_cancellation_id: 3,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "09:15",
          full_name: "Lucas Lutrario",
          phone_number: "5773308409",
        },
        {
          turn_date: "2023-12-06",
          reservation_date: "2023-11-25",
          reservation_time: "14:00",
          confirmation_id: "cancelled",
          reason_cancellation_id: 4,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "17:30",
          full_name: "Juan Lezcano",
          phone_number: "9495715492",
        },
        {
          turn_date: "2023-06-27",
          reservation_date: "2023-06-16",
          reservation_time: "21:15",
          confirmation_id: "confirmed",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "09:00",
          full_name: "Juan Pablo Lezcano",
          phone_number: "8738430333",
        },
        {
          turn_date: "2023-09-27",
          reservation_date: "2023-09-13",
          reservation_time: "21:30",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "08:15",
          full_name: "Juan Escalera",
          phone_number: "6782182725",
        },
        {
          turn_date: "2023-03-15",
          reservation_date: "2023-03-13",
          reservation_time: "12:45",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "19:45",
          full_name: "Juan Glave",
          phone_number: "9744921898",
        },
        {
          turn_date: "2023-12-22",
          reservation_date: "2023-12-08",
          reservation_time: "11:30",
          confirmation_id: "cancelled",
          reason_cancellation_id: 1,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "15:30",
          full_name: "Rodrigo Lezcano",
          phone_number: "7393003908",
        },
        {
          turn_date: "2023-09-22",
          reservation_date: "2023-09-21",
          reservation_time: "19:30",
          confirmation_id: "cancelled",
          reason_cancellation_id: 3,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "18:15",
          full_name: "Lucas Escalera",
          phone_number: "5597206580",
        },
        {
          turn_date: "2023-07-06",
          reservation_date: "2023-07-05",
          reservation_time: "19:00",
          confirmation_id: "pending",
          reason_cancellation_id: undefined,
          user_id: 1,
          branch_office_id: 2,
          horary_id: "09:15",
          full_name: "Rodrigo Escalera",
          phone_number: "1520970032",
        },
        {
          turn_date: "2023-04-10",
          reservation_date: "2023-04-04",
          reservation_time: "18:15",
          confirmation_id: "cancelled",
          reason_cancellation_id: 5,
          user_id: 1,
          branch_office_id: 1,
          horary_id: "16:00",
          full_name: "Rodrigo Lutrario",
          phone_number: "2762528614",
        },
      ];
      return Turn.bulkCreate(turnsToCreate);
    }
    return Promise.resolve(); // No es necesario devolver nada si ya hay razones de cancelacióon
  });

module.exports = Turn;
